// Code generated by solo-kit. DO NOT EDIT.

package v1

import (
	"fmt"

	github_com_solo_io_solo_kit_pkg_api_v1_resources_common_kubernetes "github.com/solo-io/solo-kit/pkg/api/v1/resources/common/kubernetes"

	"encoding/binary"
	"hash/fnv"

	"github.com/solo-io/go-utils/hashutils"
	"go.uber.org/zap"
)

type TestingSnapshot struct {
	Mocks                MockResourceList
	Fakes                FakeResourceList
	Anothermockresources AnotherMockResourceList
	Clusterresources     ClusterResourceList
	Mcts                 MockCustomTypeList
	Pods                 github_com_solo_io_solo_kit_pkg_api_v1_resources_common_kubernetes.PodList
}

func (s TestingSnapshot) Clone() TestingSnapshot {
	return TestingSnapshot{
		Mocks:                s.Mocks.Clone(),
		Fakes:                s.Fakes.Clone(),
		Anothermockresources: s.Anothermockresources.Clone(),
		Clusterresources:     s.Clusterresources.Clone(),
		Mcts:                 s.Mcts.Clone(),
		Pods:                 s.Pods.Clone(),
	}
}

func (s TestingSnapshot) Hash() uint64 {
	return hashutils.HashAll(
		s.hashMocks(),
		s.hashFakes(),
		s.hashAnothermockresources(),
		s.hashClusterresources(),
		s.hashMcts(),
		s.hashPods(),
	)
}

func (s TestingSnapshot) hashMocks() uint64 {
	hasher := fnv.New64()
	var int64buf [8]byte
	for _, element := range s.Mocks {
		hashValue := hashutils.HashAll(element)
		binary.LittleEndian.PutUint64(int64buf[:], hashValue)
		hasher.Write(int64buf[:])
	}

	return hasher.Sum64()
}

func (s TestingSnapshot) hashFakes() uint64 {
	hasher := fnv.New64()
	var int64buf [8]byte
	for _, element := range s.Fakes {
		hashValue := hashutils.HashAll(element)
		binary.LittleEndian.PutUint64(int64buf[:], hashValue)
		hasher.Write(int64buf[:])
	}

	return hasher.Sum64()
}

func (s TestingSnapshot) hashAnothermockresources() uint64 {
	hasher := fnv.New64()
	var int64buf [8]byte
	for _, element := range s.Anothermockresources {
		hashValue := hashutils.HashAll(element)
		binary.LittleEndian.PutUint64(int64buf[:], hashValue)
		hasher.Write(int64buf[:])
	}

	return hasher.Sum64()
}

func (s TestingSnapshot) hashClusterresources() uint64 {
	hasher := fnv.New64()
	var int64buf [8]byte
	for _, element := range s.Clusterresources {
		hashValue := hashutils.HashAll(element)
		binary.LittleEndian.PutUint64(int64buf[:], hashValue)
		hasher.Write(int64buf[:])
	}

	return hasher.Sum64()
}

func (s TestingSnapshot) hashMcts() uint64 {
	hasher := fnv.New64()
	var int64buf [8]byte
	for _, element := range s.Mcts {
		hashValue := hashutils.HashAll(element)
		binary.LittleEndian.PutUint64(int64buf[:], hashValue)
		hasher.Write(int64buf[:])
	}

	return hasher.Sum64()
}

func (s TestingSnapshot) hashPods() uint64 {
	hasher := fnv.New64()
	var int64buf [8]byte
	for _, element := range s.Pods {
		hashValue := hashutils.HashAll(element)
		binary.LittleEndian.PutUint64(int64buf[:], hashValue)
		hasher.Write(int64buf[:])
	}

	return hasher.Sum64()
}

func (s TestingSnapshot) HashFields() []zap.Field {
	var fields []zap.Field
	fields = append(fields, zap.Uint64("mocks", s.hashMocks()))
	fields = append(fields, zap.Uint64("fakes", s.hashFakes()))
	fields = append(fields, zap.Uint64("anothermockresources", s.hashAnothermockresources()))
	fields = append(fields, zap.Uint64("clusterresources", s.hashClusterresources()))
	fields = append(fields, zap.Uint64("mcts", s.hashMcts()))
	fields = append(fields, zap.Uint64("pods", s.hashPods()))

	return append(fields, zap.Uint64("snapshotHash", s.Hash()))
}

type TestingSnapshotStringer struct {
	Version              uint64
	Mocks                []string
	Fakes                []string
	Anothermockresources []string
	Clusterresources     []string
	Mcts                 []string
	Pods                 []string
}

func (ss TestingSnapshotStringer) String() string {
	s := fmt.Sprintf("TestingSnapshot %v\n", ss.Version)

	s += fmt.Sprintf("  Mocks %v\n", len(ss.Mocks))
	for _, name := range ss.Mocks {
		s += fmt.Sprintf("    %v\n", name)
	}

	s += fmt.Sprintf("  Fakes %v\n", len(ss.Fakes))
	for _, name := range ss.Fakes {
		s += fmt.Sprintf("    %v\n", name)
	}

	s += fmt.Sprintf("  Anothermockresources %v\n", len(ss.Anothermockresources))
	for _, name := range ss.Anothermockresources {
		s += fmt.Sprintf("    %v\n", name)
	}

	s += fmt.Sprintf("  Clusterresources %v\n", len(ss.Clusterresources))
	for _, name := range ss.Clusterresources {
		s += fmt.Sprintf("    %v\n", name)
	}

	s += fmt.Sprintf("  Mcts %v\n", len(ss.Mcts))
	for _, name := range ss.Mcts {
		s += fmt.Sprintf("    %v\n", name)
	}

	s += fmt.Sprintf("  Pods %v\n", len(ss.Pods))
	for _, name := range ss.Pods {
		s += fmt.Sprintf("    %v\n", name)
	}

	return s
}

func (s TestingSnapshot) Stringer() TestingSnapshotStringer {
	return TestingSnapshotStringer{
		Version:              s.Hash(),
		Mocks:                s.Mocks.NamespacesDotNames(),
		Fakes:                s.Fakes.NamespacesDotNames(),
		Anothermockresources: s.Anothermockresources.NamespacesDotNames(),
		Clusterresources:     s.Clusterresources.Names(),
		Mcts:                 s.Mcts.NamespacesDotNames(),
		Pods:                 s.Pods.NamespacesDotNames(),
	}
}
