apiVersion: apps/v1beta2
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "control_plane.fullname" . }}
  labels:
    gloo: control-plane
    chart: {{ template "gloo-ee.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.control_plane.replicaCount }}
  selector:
    matchLabels:
      gloo: control-plane
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        gloo: control-plane
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: control-plane
          image: "{{ .Values.control_plane.image.repository }}:{{ .Values.control_plane.image.tag }}"
          imagePullPolicy: {{ .Values.control_plane.image.pullPolicy }}
          ports:
            - name: grpc-ads
              containerPort: {{ .Values.control_plane.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.control_plane.resources | indent 12 }}
    {{- with .Values.control_plane.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.control_plane.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.control_plane.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "control_plane.fullname" . }}
  labels:
    gloo: control-plane
    release: {{ .Release.Name }}
spec:
  ports:
    - port: {{ .Values.control_plane.port }}
      protocol: TCP
      name: grpc-ads
  selector:
    gloo: control-plane
    release: {{ .Release.Name }}