// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: metadata.proto

package core

import (
	bytes "bytes"
	fmt "fmt"
	math "math"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

//*
// Metadata contains general properties of resources for purposes of versioning, annotating, and namespacing.
type Metadata struct {
	//
	//Name of the resource.
	//
	//Names must be unique and follow the following syntax rules:
	//
	//One or more lowercase rfc1035/rfc1123 labels separated by '.' with a maximum length of 253 characters.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Namespace is used for the namespacing of resources.
	Namespace string `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// GenerateName is an optional prefix, used by the server, to generate a
	// unique name ONLY IF the Name field has not been provided.
	GenerateName string `protobuf:"bytes,8,opt,name=generate_name,json=generateName,proto3" json:"generate_name,omitempty"`
	// Cluster indicates the cluster this resource belongs to
	// Cluster is only applicable in certain contexts, e.g. Kubernetes
	// An empty string here refers to the local cluster
	Cluster string `protobuf:"bytes,7,opt,name=cluster,proto3" json:"cluster,omitempty"`
	// An opaque value that represents the internal version of this object that can
	// be used by clients to determine when objects have changed.
	ResourceVersion string `protobuf:"bytes,4,opt,name=resource_version,json=resourceVersion,proto3" json:"resource_version,omitempty" testdiff:"ignore"`
	// Map of string keys and values that can be used to organize and categorize
	// (scope and select) objects. Some resources contain `selectors` which
	// can be linked with other resources by their labels
	Labels map[string]string `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Annotations is an unstructured key value map stored with a resource that may be
	// set by external tools to store and retrieve arbitrary metadata.
	Annotations          map[string]string `protobuf:"bytes,6,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{0}
}
func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Metadata) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Metadata) GetGenerateName() string {
	if m != nil {
		return m.GenerateName
	}
	return ""
}

func (m *Metadata) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *Metadata) GetResourceVersion() string {
	if m != nil {
		return m.ResourceVersion
	}
	return ""
}

func (m *Metadata) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Metadata) GetAnnotations() map[string]string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

func init() {
	proto.RegisterType((*Metadata)(nil), "core.solo.io.Metadata")
	proto.RegisterMapType((map[string]string)(nil), "core.solo.io.Metadata.AnnotationsEntry")
	proto.RegisterMapType((map[string]string)(nil), "core.solo.io.Metadata.LabelsEntry")
}

func init() { proto.RegisterFile("metadata.proto", fileDescriptor_56d9f74966f40d04) }

var fileDescriptor_56d9f74966f40d04 = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xcf, 0x4a, 0xeb, 0x40,
	0x14, 0xc6, 0x49, 0xd3, 0xbf, 0xd3, 0xde, 0x7b, 0x7b, 0x87, 0x0a, 0x43, 0x11, 0x2d, 0x71, 0x61,
	0x37, 0x26, 0xa8, 0x08, 0x5a, 0x41, 0xb4, 0xe0, 0x42, 0x50, 0x17, 0x5d, 0xb8, 0x70, 0x53, 0xa6,
	0xe9, 0x69, 0x1c, 0x9a, 0xce, 0x09, 0x33, 0x93, 0x42, 0xdf, 0xc8, 0xb7, 0xf0, 0x4d, 0x5c, 0xf8,
	0x08, 0x3e, 0x81, 0x64, 0xd2, 0xd0, 0x22, 0xb8, 0x70, 0x35, 0x67, 0xce, 0xf9, 0x7d, 0x5f, 0xf2,
	0x1d, 0x86, 0xfc, 0x5d, 0x80, 0xe1, 0x53, 0x6e, 0xb8, 0x9f, 0x28, 0x34, 0x48, 0x5b, 0x21, 0x2a,
	0xf0, 0x35, 0xc6, 0xe8, 0x0b, 0xec, 0x76, 0x22, 0x8c, 0xd0, 0x0e, 0x82, 0xac, 0xca, 0x19, 0xef,
	0xcd, 0x25, 0xf5, 0x87, 0xb5, 0x8c, 0x52, 0x52, 0x96, 0x7c, 0x01, 0xac, 0xd4, 0x73, 0xfa, 0x8d,
	0x91, 0xad, 0xe9, 0x2e, 0x69, 0x64, 0xa7, 0x4e, 0x78, 0x08, 0xcc, 0xb5, 0x83, 0x4d, 0x83, 0x1e,
	0x90, 0x3f, 0x11, 0x48, 0x50, 0xdc, 0xc0, 0xd8, 0x4a, 0xeb, 0x96, 0x68, 0x15, 0xcd, 0xc7, 0xcc,
	0x82, 0x91, 0x5a, 0x18, 0xa7, 0xda, 0x80, 0x62, 0x35, 0x3b, 0x2e, 0xae, 0xf4, 0x9a, 0xb4, 0x15,
	0x68, 0x4c, 0x55, 0x08, 0xe3, 0x25, 0x28, 0x2d, 0x50, 0xb2, 0x72, 0x86, 0x0c, 0x77, 0x3e, 0xdf,
	0xf7, 0xff, 0x1b, 0xd0, 0x66, 0x2a, 0x66, 0xb3, 0x81, 0x27, 0x22, 0x89, 0x0a, 0xbc, 0xd1, 0xbf,
	0x02, 0x7f, 0xca, 0x69, 0x3a, 0x20, 0xd5, 0x98, 0x4f, 0x20, 0xd6, 0xac, 0xd2, 0x73, 0xfb, 0xcd,
	0x13, 0xcf, 0xdf, 0x0e, 0xed, 0x17, 0xd1, 0xfc, 0x7b, 0x0b, 0xdd, 0x4a, 0xa3, 0x56, 0xa3, 0xb5,
	0x82, 0xde, 0x91, 0x26, 0x97, 0x12, 0x0d, 0x37, 0x02, 0xa5, 0x66, 0x55, 0x6b, 0x70, 0xf8, 0x83,
	0xc1, 0xcd, 0x86, 0xcc, 0x5d, 0xb6, 0xb5, 0xdd, 0x0b, 0xd2, 0xdc, 0xfa, 0x02, 0x6d, 0x13, 0x77,
	0x0e, 0x2b, 0xe6, 0xd8, 0xb4, 0x59, 0x49, 0x3b, 0xa4, 0xb2, 0xe4, 0x71, 0x5a, 0xec, 0x36, 0xbf,
	0x0c, 0x4a, 0xe7, 0x4e, 0xf7, 0x8a, 0xb4, 0xbf, 0x7b, 0xff, 0x46, 0x3f, 0xbc, 0x7c, 0xfd, 0xd8,
	0x73, 0x9e, 0xcf, 0x22, 0x61, 0x5e, 0xd2, 0x89, 0x1f, 0xe2, 0x22, 0xc8, 0xfe, 0xfd, 0x48, 0x60,
	0x7e, 0xce, 0x85, 0x09, 0x92, 0x79, 0x14, 0xf0, 0x44, 0x04, 0xcb, 0xe3, 0xa0, 0xd8, 0x9f, 0x0e,
	0xb2, 0x98, 0x93, 0xaa, 0x7d, 0x05, 0xa7, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x69, 0x9c, 0xd4,
	0xdf, 0x3b, 0x02, 0x00, 0x00,
}

func (this *Metadata) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Metadata)
	if !ok {
		that2, ok := that.(Metadata)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.Namespace != that1.Namespace {
		return false
	}
	if this.GenerateName != that1.GenerateName {
		return false
	}
	if this.Cluster != that1.Cluster {
		return false
	}
	if this.ResourceVersion != that1.ResourceVersion {
		return false
	}
	if len(this.Labels) != len(that1.Labels) {
		return false
	}
	for i := range this.Labels {
		if this.Labels[i] != that1.Labels[i] {
			return false
		}
	}
	if len(this.Annotations) != len(that1.Annotations) {
		return false
	}
	for i := range this.Annotations {
		if this.Annotations[i] != that1.Annotations[i] {
			return false
		}
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
