// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ref.proto

package core

import (
	fmt "fmt"
	math "math"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// A way to reference resources across namespaces
type ResourceRef struct {
	// name of the target resource
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// namespace of the target resource
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

func (m *ResourceRef) Reset()         { *m = ResourceRef{} }
func (m *ResourceRef) String() string { return proto.CompactTextString(m) }
func (*ResourceRef) ProtoMessage()    {}
func (*ResourceRef) Descriptor() ([]byte, []int) {
	return fileDescriptor_65d958559ea81b29, []int{0}
}
func (m *ResourceRef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceRef.Unmarshal(m, b)
}
func (m *ResourceRef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceRef.Marshal(b, m, deterministic)
}
func (m *ResourceRef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceRef.Merge(m, src)
}
func (m *ResourceRef) XXX_Size() int {
	return xxx_messageInfo_ResourceRef.Size(m)
}
func (m *ResourceRef) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceRef.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceRef proto.InternalMessageInfo

func (m *ResourceRef) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ResourceRef) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

// A way to reference resources across clusters
type ClusterResourceRef struct {
	// name of the target resource
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// namespace of the target resource
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// cluster name of the target resource
	Cluster string `protobuf:"bytes,3,opt,name=cluster,proto3" json:"cluster,omitempty"`
}

func (m *ClusterResourceRef) Reset()         { *m = ClusterResourceRef{} }
func (m *ClusterResourceRef) String() string { return proto.CompactTextString(m) }
func (*ClusterResourceRef) ProtoMessage()    {}
func (*ClusterResourceRef) Descriptor() ([]byte, []int) {
	return fileDescriptor_65d958559ea81b29, []int{1}
}
func (m *ClusterResourceRef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterResourceRef.Unmarshal(m, b)
}
func (m *ClusterResourceRef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterResourceRef.Marshal(b, m, deterministic)
}
func (m *ClusterResourceRef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterResourceRef.Merge(m, src)
}
func (m *ClusterResourceRef) XXX_Size() int {
	return xxx_messageInfo_ClusterResourceRef.Size(m)
}
func (m *ClusterResourceRef) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterResourceRef.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterResourceRef proto.InternalMessageInfo

func (m *ClusterResourceRef) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ClusterResourceRef) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ClusterResourceRef) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func init() {
	proto.RegisterType((*ResourceRef)(nil), "core.solo.io.ResourceRef")
	proto.RegisterType((*ClusterResourceRef)(nil), "core.solo.io.ClusterResourceRef")
}

func init() { proto.RegisterFile("ref.proto", fileDescriptor_65d958559ea81b29) }

var fileDescriptor_65d958559ea81b29 = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2c, 0x4a, 0x4d, 0xd3,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x49, 0xce, 0x2f, 0x4a, 0xd5, 0x2b, 0xce, 0xcf, 0xc9,
	0xd7, 0xcb, 0xcc, 0x97, 0x12, 0x49, 0xcf, 0x4f, 0xcf, 0x07, 0x4b, 0xe8, 0x83, 0x58, 0x10, 0x35,
	0x4a, 0xbe, 0x5c, 0xdc, 0x41, 0xa9, 0xc5, 0xf9, 0xa5, 0x45, 0xc9, 0xa9, 0x41, 0xa9, 0x69, 0x42,
	0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6,
	0x90, 0x0c, 0x17, 0x27, 0x88, 0x2e, 0x2e, 0x48, 0x4c, 0x4e, 0x95, 0x60, 0x02, 0x4b, 0x20, 0x04,
	0xac, 0x78, 0x2e, 0x2c, 0x94, 0x67, 0x98, 0xb0, 0x48, 0x9e, 0x61, 0xc6, 0x22, 0x79, 0x06, 0xa5,
	0x3c, 0x2e, 0x21, 0xe7, 0x9c, 0xd2, 0xe2, 0x92, 0xd4, 0x22, 0x8a, 0x4c, 0x15, 0x92, 0xe0, 0x62,
	0x4f, 0x86, 0x98, 0x23, 0xc1, 0x0c, 0x96, 0x83, 0x71, 0x51, 0xed, 0x73, 0xb2, 0x5e, 0xf1, 0x48,
	0x8e, 0x31, 0xca, 0x34, 0x3d, 0xb3, 0x24, 0xa3, 0x34, 0x49, 0x2f, 0x39, 0x3f, 0x57, 0x1f, 0xe4,
	0x5d, 0xdd, 0xcc, 0x7c, 0x08, 0x9d, 0x9d, 0x59, 0xa2, 0x5f, 0x90, 0x9d, 0xae, 0x9f, 0x58, 0x90,
	0xa9, 0x5f, 0x66, 0xa8, 0x5f, 0x04, 0x75, 0x53, 0xb1, 0x3e, 0x28, 0x64, 0x92, 0xd8, 0xc0, 0x41,
	0x60, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xde, 0x67, 0x90, 0x68, 0x33, 0x01, 0x00, 0x00,
}

func (this *ResourceRef) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ResourceRef)
	if !ok {
		that2, ok := that.(ResourceRef)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.Namespace != that1.Namespace {
		return false
	}
	return true
}
func (this *ClusterResourceRef) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ClusterResourceRef)
	if !ok {
		that2, ok := that.(ClusterResourceRef)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.Namespace != that1.Namespace {
		return false
	}
	if this.Cluster != that1.Cluster {
		return false
	}
	return true
}
