name: pull_request

on:
  push:
    branches:
    - 'master'
  pull_request:

jobs:
  test:
    name: Tests
    runs-on: ubuntu-18.04
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.4.0
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go
    - uses: azure/setup-kubectl@v1
      with:
        version: 'v1.18.0'
    - uses: engineerd/setup-kind@v0.3.0
    - name: Install Protoc
      uses: arduino/setup-protoc@v1.1.0
      with:
        version: '3.6.1'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: install consul
      run: |
        wget -q https://releases.hashicorp.com/consul/1.4.0/consul_1.4.0_linux_amd64.zip && \
        unzip -q consul_1.4.0_linux_amd64.zip && \
        sudo mv consul /usr/local/bin/ && \
        rm consul_1.4.0_linux_amd64.zip
    - name: make update deps
      run: |
        make update-deps
    - name: Run tests
      env:
        CONSUL_BINARY: /usr/local/bin/consul
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RUN_KUBE_TESTS: "1"
        RUN_VAULT_TESTS: "1"
        RUN_CONSUL_TESTS: "1"
        SKIP_MOCK_GEN: "1"
      run: |
        go get -v github.com/onsi/ginkgo/ginkgo@v1.12.0 && export PATH=$PATH:$(go env GOPATH)/bin/
        ginkgo -r -p -failFast -tags solokit
